stages:
  cleaning:
    cmd: python cleaning.py --data_path data_artifacts/spam_mail_data.csv --text_column
      Message --target_column Category
    deps:
    - cleaning.py
    - data_artifacts/spam_mail_data.csv
    outs:
    - data_artifacts/cleaned_data.csv
    - dictionary/id_to_value.pkl
    - dictionary/value_to_id.pkl
  exploration:
    cmd: python exploration.py --data_path data_artifacts/cleaned_data.csv --text_column
      Message --target_column Category
    deps:
    - data_artifacts/cleaned_data.csv
    - exploration.py
    outs:
    - eda_results/class_distribution_chart.png
  train:
    cmd: python train.py --data_path data_artifacts/cleaned_data.csv --independent_feature
      Message --dependent_feature Category_id --test_size 0.2
    deps:
    - data_artifacts/cleaned_data.csv
    - train.py
    outs:
    - data_artifacts/test_set.csv
    - model/model_pipeline.pkl
  test:
    cmd: python test.py --test_set data_artifacts/test_set.csv --independent_feature
      Message --dependent_feature Category_id
    deps:
    - data_artifacts/test_set.csv
    - test.py
    outs:
    - results/classification_reports.png
    - results/confusion_matrix.png
